Options:
  experimental features: false #Turn on experimental features
  debug: false
  updater: true
  command:
    killstreak: true
    level: true
    hunter: true
    prestige: true
    bounty: true
  levels:
    top: 5
    discord: false
    rewards: true
    message:
      enabled: true
      receiver: all # values: all and player
      every: 5 # send the message every X levels
    title:
      receiver: player # values: all and player
      enabled: true
      every: 5 # show the title every X levels
      fade in: 10
      stay: 20
      fade out: 10
  killstreak:
    top: 5
    discord: false
    rewards: true
    message:
      receiver: all # values: all and player
      enabled: true
      every: 10 # send the message every X killstreak
  kills:
    top: 5
    discord: false
    rewards: true
    # Set true, so you don't have to set rewards for every kill
    # the closest kill will be used e.g. if the player have 10 kills and in the config
    # only exists the reward of 3 and 20 then the player will get kill 3 rewards
    closest: true
  bounty:
    enabled: false
    base: 300.0
    killstreak: 10
    killstreak enabled: true
    message: true
    every: 10
    percentage: 3.5
    percentage enabled: true
  # File, MySQL, PostgreSQL, SQLite, MongoDB
  # Select in what type you want your data to be stored
  # File is recommended
  #SQL section is for MySQL(or MariaDB) and PostgreSQL
  #Default PostgreSQL port: 5432
  #Default MySQL and MariaDB port: 3306
  #Default MongoDB port: 27017
  database:
    type: File
    SQLite:
      file name: hunter
    SQL:
      host: localhost
      port: 3306
      user: youruser
      password: "yourpassword"
      database: hunter
      table name: "hunter_users"
    MongoDB:
      host: "localhost"
      port: 27017
      user: youruser
      password: "yourpassword"
      database: "hunter"
      collection: "hunter_users"
  hologram:
    enabled: false
    type: ProtocolLib #ProtocolLib or HolographicDisplays

Rewards:
  level up:
    5:
      commands:
        - broadcast 5 levels
  kills:
    10:
      commands:
        - broadcast 10 kills
  killstreak:
    10:
      commands:
        - broadcast 10 killstreak

Levels:
  1: 1
  2: 2
  3: 5
  4: 6
  5: 7

# Hologram examples
# Suggest more placeholders on GitHub
Holograms:
  leveltop:
    - 'Top Players by Level'
    - '%toplevel-1% - %level-1%'
    - '%toplevel-2% - %level-2%'
    - '%toplevel-3% - %level-3%'
    - '%toplevel-4% - %level-4%'
    - '%toplevel-5% - %level-5%'
  killstop:
    - 'Top Players by Kills'
    - '%topkills-1% - %kills-1%'
    - '%topkills-2% - %kills-2%'
    - '%topkills-3% - %kills-3%'
    - '%topkills-4% - %kills-4%'
    - '%topkills-5% - %kills-5%'
  killstreaktop:
    - 'Top Players by KillStreak'
    - '%topkillstreak-1% - %killstreak-1%'
    - '%topkillstreak-2% - %killstreak-2%'
    - '%topkillstreak-3% - %killstreak-3%'
    - '%topkillstreak-4% - %killstreak-4%'
    - '%topkillstreak-5% - %killstreak-5%'